name: flutter_where_money_go
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  flutter_launcher_icons: ^0.13.1
  dio: ^5.4.2
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.5
  loader_overlay: ^4.0.0
  loading_animation_widget: ^1.2.1
  get_it: ^7.6.7
  awesome_snackbar_content: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true